import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import {
  libreBaskerville,
  mourich,
  rocaOne,
  theYoungest,
} from "@/lib/fonts/fonts";
import { Footer } from "@/components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${libreBaskerville.variable} ${theYoungest.variable} ${mourich.variable} ${rocaOne.variable} antialiased`}
      >
        <div className="bg-toby-frosted-pearl flex flex-col min-h-screen h-full">
          {/* Change with navbar later */}
          <Navbar />
          <div className="flex justify-center items-center h-[93px] lg:h-[118px] mt-[42px] mb-7 mx-[46px]"></div>
          <main className="mb-7 mx-8 lg:mx-8 lg:flex lg:content-center lg:max-w-[1440px] xl:mx-auto">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
